---
title: "RStudio Team QuickStart VM - Help"
---

<!--html_preserve-->
<script type="text/javascript">
function set_version() {
    const Http = new XMLHttpRequest();
    const url=window.location.origin + '/version';
    Http.open("GET", url);

    // important to create this listenter _before_ we send it... #asyncprobs
    Http.onreadystatechange=(e)=>{
      var obj = document.getElementById("quickstart-version");
      if (Http.status == 200 && Http.responseText != "") {
        obj.innerHTML = obj.innerHTML.replace('Unknown', Http.responseText);
      }
    }
    Http.send();
}
window.onload = function() {
  set_version()
}
</script>
<!--/html_preserve-->

## Help

### Support and Feedback

Support and feedback related to the QuickStart should be sent via the [RStudio Community forums](https://community.rstudio.com/tags/c/r-admin/quickstart). Posts should be submitted to the `R Admins` category and tagged with the `quickstart` tag.

Please note that professional support is not available for the QuickStart.

### Frequently Asked Questions

View a list of [frequently asked questions](https://support.rstudio.com/hc/en-us/articles/360014001734-RStudio-Quickstart-FAQ) related to the RStudio QuickStart.

### RStudio Documentation

View documentation for all RStudio products on the [RStudio Documentation](http://docs.rstudio.com/) page, or by accessing the documentation links from within the products in the QuickStart.

You can also view a list of curated [RStudio Connect Support Documentation](https://support.rstudio.com/hc/en-us/sections/204688508-RStudio-Connect).

<hr>

## About

### Version { #quickstart-version }

Quickstart VM Version: Unknown

### Intended Use

The QuickStart is primarily intended as a demo environment and is **not** supported for use in any production capacity. For more information about using RStudio Professional products on your own enterprise infrastructure, please [contact our sales team](https://www.rstudio.com/about/contact-sales/).

### Webmail Server

A <a href="webmail/" target="_blank">webmail server</a> is available within the QuickStart to demonstrate RStudio Connect’s capability for sending automated, customized emails.

In the QuickStart, all email from RStudio products is configured to be sent into a single mailbox. In an actual implementation, RStudio Products can integrate securely with your email infrastructure to ensure that information remains private.

<!-- Terms of Use from https://www.rstudio.com/about/quickstart/ -->

<div id="terms-of-use-for-this-quickstart-virtual-machine" class="section level3">
<h3>Terms of use</h3>
<a href="#pro">RStudio Professional Products</a> are licensed pursuant to the <a href="https://www.rstudio.com/about/eula/">RStudio End User License Agreement</a>. By downloading, installing or otherwise using the <a href="#pro">RStudio Professional Products</a>, you agree to the terms of the <a href="https://www.rstudio.com/about/eula/">RStudio End User License Agreement</a>. If you do not agree to the <a href="https://www.rstudio.com/about/eula/">RStudio End User License Agreement</a>, do not download, install or use the <a href="#pro">RStudio Professional Products</a>. <a href="#pro">RStudio Professional Products</a> are provided on a stand-alone basis and separate from the other software programs included on this QuickStart Virtual Machine.

<a href="#oss">Open Source Software Programs</a> are included as separate programs on this QuickStart Virtual Machine as a convenience to the end user. <a href="#oss">Open Source Software Programs</a> are licensed pursuant to their respective licenses which can be obtained by clicking the name of the <a href="#oss">Open Source Software Programs</a> set forth below. <a href="#oss">Open Source Software Programs</a> are provided on a stand-alone basis and separate from <a href="#pro">RStudio Professional Products</a> included on this QuickStart Virtual Machine.

RStudio is not the licensor of the <a href="#oss">Open Source Software Programs</a> and assumes no liability or obligation with respect to the <a href="#oss">Open Source Software Programs</a>, which are provided “as is” and which you acknowledge you are using at your own risk. Accordingly, RStudio expressly disclaims any and all representations and warranties, express, implied and statutory, including without limitation expressly disclaiming the implied warranties of title, noninfringement, fitness for a particular purpose, and merchantability. RStudio shall have no liability to you arising out of or related to the <a href="#oss">Open Source Software Programs</a> or your use thereof and expressly disclaims any and all direct, indirect, consequential, exemplary, incidental, special and punitive damages arising out of or related to the <a href="#oss">Open Source Software Programs</a> and your use of thereof.

</div>
<div id="rstudio-professional-products" class="section level3">
<h3><a name="pro"></a><span style="color: #404040;">RStudio Professional Products</span></h3>
<ul>
 	<li><a href="https://www.rstudio.com/products/rstudio-server-pro/evaluation/">RStudio Server Pro</a></li>
 	<li><a href="https://www.rstudio.com/products/connect/evaluation/">RStudio Connect</a></li>
 	<li><a href="https://www.rstudio.com/products/package-manager/eval/">RStudio Package Manager</a></li>
</ul>
</div>
<div id="open-source-software-programs" class="section level3">
<h3><a name="oss"></a><span style="color: #404040;">Open Source Software Programs</span></h3>
<ul>
 	<li><a href="https://www.r-project.org/Licenses/">R</a></li>
 	<li><a href="https://roundcube.net/license/">Roundcube</a></li>
 	<li><a href="https://yq.readthedocs.io/en/latest/#license">yq</a></li>
 	<li><a href="http://nginx.org/LICENSE">nginx</a></li>
 	<li><a href="https://www.ubuntu.com/licensing">Ubuntu</a> (and system libraries)
<ul>
 	<li><small>build-essential</small></li>
 	<li><small>default-jdk</small></li>
 	<li><small>gdebi-core</small></li>
 	<li><small>gfortran</small></li>
 	<li><small>git</small></li>
 	<li><small>gnome-keyring</small></li>
 	<li><small>jags</small></li>
 	<li><small>jq</small></li>
 	<li><small>libatlas3-base</small></li>
 	<li><small>libboost-all-dev</small></li>
 	<li><small>libcairo2</small></li>
 	<li><small>libcairo2-dev</small></li>
 	<li><small>libcurl4-openssl-dev</small></li>
 	<li><small>libfftw3-dev</small></li>
 	<li><small>libgdal-dev</small></li>
 	<li><small>libgraphviz-dev</small></li>
 	<li><small>libgsl-dev</small></li>
 	<li><small>libmysqlclient-dev</small></li>
 	<li><small>libnetcdf-dev</small></li>
 	<li><small>libprocps-dev</small></li>
 	<li><small>libproj-dev</small></li>
 	<li><small>libprotoc-dev</small></li>
 	<li><small>libsecret-1-dev</small></li>
 	<li><small>libquantlib0-dev</small></li>
 	<li><small>libxml2-dev</small></li>
 	<li><small>libsasl2-dev</small></li>
 	<li><small>libxt-dev</small></li>
 	<li><small>libxt6</small></li>
 	<li><small>lsb-release</small></li>
 	<li><small>net-tools</small></li>
 	<li><small>odbc-postgresql</small></li>
 	<li><small>openssh-client</small></li>
 	<li><small>protobuf-compiler</small></li>
 	<li><small>python-pip</small></li>
 	<li><small>python-dev</small></li>
 	<li><small>python-virtualenv</small></li>
 	<li><small>sudo</small></li>
 	<li><small>tdsodbc</small></li>
 	<li><small>texinfo</small></li>
 	<li><small>texlive</small></li>
 	<li><small>texlive-bibtex-extra</small></li>
 	<li><small>texlive-fonts-extra</small></li>
 	<li><small>texlive-latex-extra</small></li>
 	<li><small>texlive-xetex</small></li>
 	<li><small>unixodbc</small></li>
 	<li><small>unixodbc-dev</small></li>
 	<li><small>wget</small></li>
</ul>
</li>
</ul>
</div>
