---
title: "Legal Terms"
---

### Terms of use for this Quickstart Virtual Machine

*[RStudio Professional Products](#rstudio-professional-products) are licensed pursuant to the [RStudio End User License Agreement](https://www.rstudio.com/about/eula/). By downloading, installing or otherwise using the [RStudio Professional Products](#rstudio-professional-products), you agree to the terms of the [RStudio End User License Agreement](https://www.rstudio.com/about/eula/). If you do not agree to the [RStudio End User License Agreement](https://www.rstudio.com/about/eula/), do not download, install or use the [RStudio Professional Products](#rstudio-professional-products). [RStudio Professional Products](#rstudio-professional-products) are provided on a stand-alone basis and separate from the other software programs included on this Quickstart Virtual Machine.*

*[Open Source Software Programs](#open-source-software-programs) are included as separate programs on this Quickstart Virtual Machine as a convenience to the end user. [Open Source Software Programs](#open-source-software-programs) are licensed pursuant to their respective licenses which can be obtained by clicking the name of the [Open Source Software Programs](#open-source-software-programs) set forth below. [Open Source Software Programs](#open-source-software-programs) are provided on a stand-alone basis and separate from [RStudio Professional Products](#rstudio-professional-products) included on this Quickstart Virtual Machine.*

*RStudio is not the licensor of the [Open Source Software Programs](#open-source-software-programs) and assumes no liability or obligation with respect to the [Open Source Software Programs](#open-source-software-programs), which are provided “as is” and which you acknowledge you are using at your own risk. Accordingly, RStudio expressly disclaims any and all representations and warranties, express, implied and statutory, including without limitation expressly disclaiming the implied warranties of title, noninfringement, fitness for a particular purpose, and merchantability. RStudio shall have no liability to you arising out of or related to the [Open Source Software Programs](#open-source-software-programs) or your use thereof and expressly disclaims any and all direct, indirect, consequential, exemplary, incidental, special and punitive damages arising out of or related to the [Open Source Software Programs](#open-source-software-programs) and your use of thereof.*

#### RStudio Professional Products

* [RStudio Server Pro](https://www.rstudio.com/products/rstudio-server-pro/evaluation/)
* [RStudio Connect](https://www.rstudio.com/products/connect/evaluation/)
* [RStudio Package Manager](https://www.rstudio.com/products/package-manager/eval/)

#### Open Source Software Programs

* [R](https://www.r-project.org/Licenses/)
* [Ubuntu](https://www.ubuntu.com/licensing)
* [Roundcube](https://roundcube.net/license/)
 

